language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  
install: mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V
  
script: mvn package install -Dmaven.test.skip=true -Pproduction

after_success:
  - bash <(curl -s https://codecov.io/bash)